version: '3.5'
services:
  frontend:
    image: vidhuarora/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: vidhuarora/backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/vidhu/expense-tracker_fullstack/data/db:/data/db:rw